name: simas
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  http: any
  flutter: 
    sdk: flutter
  flutter_neumorphic: ^3.2.0
  fl_chart: ^0.55.2
  flutter_map: ^3.0.0
  latlong2: ^0.8.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/

